/**
 * `<OrderTicket>` — the surface that carries the safety model.
 *
 * Controlled (`value` + `onChange`), JSON-friendly (every number a decimal
 * string), stable handles (`data-fancy-trading-ticket-*`), observable (every
 * mutation broadcasts), and bridgeable (all the logic is in `useOrderTicket`).
 *
 * The one thing to read before changing anything here: **submitting goes
 * through `attemptSubmit`, which calls the domain's `submittable()`.** There is
 * no `if (origin === "agent")` in this file. An agent-origin intent with no
 * `Approval` throws inside the domain package, and that throw is what opens the
 * confirmation. Adding a prop that skips it would mean deleting that call.
 */

import { useState, type ReactNode } from "react";
import {
  Badge,
  Button,
  Callout,
  Input,
  Select,
  Switch,
} from "@particle-academy/react-fancy";
import type { Approval, OrderIntent } from "@particle-academy/fancy-trading";
import { SurfaceChrome } from "../../chrome/SurfaceChrome.tsx";
import { ModeMarker } from "../../chrome/ModeMarker.tsx";
import { WarningNotice } from "../../chrome/Confirm.tsx";
import { WarningRegistry } from "../../safety/warnings.ts";
import { LIVE, type Liveness, type TradingMode } from "../../safety/mode.ts";
import type { JsonRiskLimits } from "../../safety/limits.ts";
import type { Limitation } from "../../safety/limited.ts";
import { TRADING_ACTIONS, emitTradingActivity, type TradingActivityEmitter } from "../../activity.ts";
import { formatPrice } from "../../format.ts";
import { encodeSide, type DirectionPalette } from "../../direction.ts";
import type {
  AttachedOrders,
  OrderType,
  TicketEstimate,
  TicketInstrument,
  TicketValue,
  TimeInForce,
} from "./types.ts";
import {
  approveIntent,
  attemptSubmit,
  useOrderTicket,
  type TicketMarketContext,
} from "./useOrderTicket.ts";

/** Extras that travel with the intent but are not part of the domain type. */
export type SubmitExtras = {
  attached?: AttachedOrders;
  instrument: TicketInstrument;
  value: TicketValue;
};

export type OrderTicketProps = {
  /** Real money or not. Required, never defaulted. */
  mode: TradingMode;
  instrument: TicketInstrument;
  value: TicketValue;
  onChange: (value: TicketValue) => void;
  /**
   * Called with an intent that has already passed the domain gate.
   *
   * For an `agent` origin the third argument's `approval` is always present,
   * because there is no path to this callback without one.
   */
  onSubmit: (intent: OrderIntent, approval: Approval | undefined, extras: SubmitExtras) => void;
  /** Generated by the host BEFORE send, and stable across retries (§2.6). */
  clientOrderId: string;
  /**
   * Who is driving. **Set by the transport, not by the caller** — an MCP bridge
   * stamps `"agent"` at its boundary. There is no argument that changes it.
   */
  origin?: "human" | "agent";
  liveness?: Liveness;
  limits?: JsonRiskLimits;
  market?: TicketMarketContext;
  warnings?: WarningRegistry;
  scope?: string;
  limitations?: readonly Limitation[];
  /** Recomputed on every render, deliberately — see `TicketEstimate`. */
  estimate?: (intent: OrderIntent) => TicketEstimate | null;
  /** Identity recorded on the `Approval`. */
  approver?: string;
  activity?: TradingActivityEmitter | null;
  palette?: DirectionPalette;
  moneyExp?: number;
  className?: string;
  id?: string;
  now?: number;
};

const ORDER_TYPES: { value: OrderType; label: string }[] = [
  { value: "market", label: "Market" },
  { value: "limit", label: "Limit" },
  { value: "stop", label: "Stop" },
  { value: "stopLimit", label: "Stop limit" },
  { value: "trailingStop", label: "Trailing stop" },
];

const TIFS: { value: TimeInForce; label: string }[] = [
  { value: "day", label: "Day" },
  { value: "gtc", label: "GTC" },
  { value: "gtd", label: "GTD" },
  { value: "ioc", label: "IOC" },
  { value: "fok", label: "FOK" },
  { value: "opg", label: "At the open" },
  { value: "cls", label: "At the close" },
];

export function OrderTicket(props: OrderTicketProps) {
  const {
    mode,
    instrument,
    value,
    onChange,
    onSubmit,
    clientOrderId,
    origin = "human",
    liveness = LIVE,
    limitations,
    approver = "human",
    activity,
    palette,
    className,
    id,
  } = props;

  const [warnings] = useState(() => props.warnings ?? new WarningRegistry());
  const [pending, setPending] = useState<OrderIntent | null>(null);

  const ticket = useOrderTicket({
    instrument,
    value,
    mode,
    liveness,
    origin,
    clientOrderId,
    limits: props.limits,
    market: props.market,
    scope: props.scope,
    estimate: props.estimate,
    moneyExp: props.moneyExp,
    now: props.now,
  });

  const actor = { source: origin, id: origin === "agent" ? "agent" : "human" };
  const set = (patch: Partial<TicketValue>): void => {
    onChange({ ...value, ...patch });
    emitTradingActivity({
      action: TRADING_ACTIONS.TicketChange,
      surface: "ticket",
      elementId: clientOrderId,
      actor,
      emitter: activity,
      meta: { patch },
    });
  };

  const submit = (): void => {
    if (!ticket.intent || !ticket.canSubmit) return;
    const outcome = attemptSubmit(ticket.intent);
    if (outcome.kind === "needs-approval") {
      setPending(outcome.intent);
      emitTradingActivity({
        action: TRADING_ACTIONS.OrderPropose,
        surface: "ticket",
        elementId: clientOrderId,
        actor,
        emitter: activity,
        meta: { symbol: instrument.symbol, side: value.side, qty: value.qty },
      });
      return;
    }
    emitTradingActivity({
      action: TRADING_ACTIONS.OrderSubmit,
      surface: "ticket",
      elementId: clientOrderId,
      actor,
      emitter: activity,
      meta: { symbol: instrument.symbol, side: value.side, qty: value.qty },
    });
    onSubmit(outcome.intent, outcome.approval, {
      attached: ticket.attached,
      instrument,
      value,
    });
  };

  const confirmPending = (): void => {
    if (!pending) return;
    const approval = approveIntent(pending, approver);
    // Through the gate a second time, WITH the approval. If this throws, the
    // approval did not match the intent — the confused-deputy shape — and no
    // order is placed.
    const outcome = attemptSubmit(pending, approval);
    if (outcome.kind !== "submitted") return;
    setPending(null);
    emitTradingActivity({
      action: TRADING_ACTIONS.OrderSubmit,
      surface: "ticket",
      elementId: clientOrderId,
      actor: { source: "human", id: approver },
      emitter: activity,
      meta: { approvedFrom: "agent" },
    });
    onSubmit(outcome.intent, approval, { attached: ticket.attached, instrument, value });
  };

  const side = encodeSide(value.side, palette);
  const needsLimit = value.type === "limit" || value.type === "stopLimit";
  const needsTrigger = value.type === "stop" || value.type === "stopLimit";
  const needsTrail = value.type === "trailingStop";

  return (
    <SurfaceChrome
      surface="ticket"
      mode={mode}
      liveness={liveness}
      limitations={limitations}
      id={id}
      className={className}
      title={
        <span className="flex items-center gap-2">
          <span>{instrument.displaySymbol ?? instrument.symbol}</span>
          <Badge size="sm" color="zinc" variant="outline">
            {side.glyph} {side.label}
          </Badge>
        </span>
      }
    >
      <div data-fancy-trading-ticket={instrument.symbol} className="space-y-3 p-3">
        <div className="grid grid-cols-2 gap-2">
          <div data-fancy-trading-ticket-side="">
            <Select
              label="Side"
              list={[
                { value: "buy", label: "Buy" },
                { value: "sell", label: "Sell" },
              ]}
              value={value.side}
              onChange={(e) => set({ side: e.currentTarget.value as TicketValue["side"] })}
            />
          </div>
          <div data-fancy-trading-ticket-qty="">
            <Input
              label="Quantity"
              inputMode="decimal"
              value={value.qty}
              onChange={(e) => set({ qty: e.currentTarget.value })}
            />
          </div>
        </div>

        <div data-fancy-trading-ticket-type="">
          <Select
            label="Order type"
            list={ORDER_TYPES}
            value={value.type}
            onChange={(e) => set({ type: e.currentTarget.value as OrderType })}
          />
        </div>

        <div className="grid grid-cols-2 gap-2">
          {needsLimit && (
            <div data-fancy-trading-ticket-limit-price="">
              <Input
                label="Limit price"
                inputMode="decimal"
                value={value.limitPrice ?? ""}
                onChange={(e) => set({ limitPrice: e.currentTarget.value })}
              />
            </div>
          )}
          {needsTrigger && (
            <div data-fancy-trading-ticket-trigger-price="">
              <Input
                label="Trigger price"
                inputMode="decimal"
                value={value.triggerPrice ?? ""}
                onChange={(e) => set({ triggerPrice: e.currentTarget.value })}
              />
            </div>
          )}
          {needsTrail && (
            <div data-fancy-trading-ticket-trail-offset="">
              <Input
                label="Trail offset"
                inputMode="decimal"
                value={value.trailOffset ?? ""}
                onChange={(e) => set({ trailOffset: e.currentTarget.value })}
              />
            </div>
          )}
        </div>

        <div className="grid grid-cols-2 gap-2">
          <div data-fancy-trading-ticket-tif="">
            <Select
              label="Time in force"
              list={TIFS}
              value={value.tif}
              onChange={(e) => set({ tif: e.currentTarget.value as TimeInForce })}
            />
          </div>
          <div className="flex items-end gap-4 pb-1">
            <Switch
              data-fancy-trading-ticket-reduce-only=""
              label="Reduce only"
              checked={value.reduceOnly ?? false}
              onCheckedChange={(checked) => set({ reduceOnly: checked })}
            />
            <Switch
              data-fancy-trading-ticket-post-only=""
              label="Post only"
              checked={value.postOnly ?? false}
              onCheckedChange={(checked) => set({ postOnly: checked })}
            />
          </div>
        </div>

        {value.attached ? <AttachedSummary attached={value.attached} /> : null}

        {ticket.warnings.map((w) => (
          <WarningNotice
            key={w.id}
            registry={warnings}
            id={w.id}
            scope={ticket.scope}
            message={w.message}
            detail={w.detail}
          />
        ))}

        {ticket.estimate ? (
          <Estimate estimate={ticket.estimate} currency={instrument.currency} />
        ) : null}

        {ticket.blockedReason ? (
          <Callout data-fancy-trading-ticket-blocked="" color="red">
            <p className="text-sm">{ticket.blockedReason}</p>
            {ticket.verdict?.unevaluated.length ? (
              <p className="mt-1 text-xs opacity-80">
                Not checked, for want of the data to check them:{" "}
                {ticket.verdict.unevaluated.join(", ")}.
              </p>
            ) : null}
          </Callout>
        ) : ticket.verdict?.unevaluated.length ? (
          <p className="text-xs text-secondary-500">
            Limits not checked, for want of the data to check them:{" "}
            {ticket.verdict.unevaluated.join(", ")}.
          </p>
        ) : null}

        <Button
          data-fancy-trading-ticket-submit=""
          color={value.side === "buy" ? "green" : "red"}
          disabled={!ticket.canSubmit}
          onClick={submit}
          className="w-full"
        >
          {origin === "agent" ? "Propose" : side.label === "buy" ? "Buy" : "Sell"}{" "}
          {value.qty} {instrument.displaySymbol ?? instrument.symbol}
          {ticket.intent?.limitPrice
            ? ` @ ${formatPrice(ticket.intent.limitPrice, instrument.priceDisplay)}`
            : ""}
        </Button>
      </div>

      {pending ? (
        <ApprovalDialog
          intent={pending}
          instrument={instrument}
          mode={mode}
          onAccept={confirmPending}
          onReject={() => setPending(null)}
        />
      ) : null}
    </SurfaceChrome>
  );
}

function AttachedSummary({ attached }: { attached: AttachedOrders }) {
  return (
    <div data-fancy-trading-ticket-attached="" className="rounded border border-secondary-200 p-2 text-xs dark:border-secondary-800">
      <p className="font-medium">Attached orders</p>
      {attached.takeProfit ? <p>Take profit at {attached.takeProfit.limitPrice}</p> : null}
      {attached.stopLoss ? (
        <p>
          Stop loss at {attached.stopLoss.triggerPrice}
          {attached.stopLoss.limitPrice ? `, limit ${attached.stopLoss.limitPrice}` : ""}
        </p>
      ) : null}
      {attached.ocoEnforcedBy ? (
        <p className="mt-1 opacity-80">
          {attached.ocoEnforcedBy === "venue"
            ? "One-cancels-other is enforced by the venue — it holds even if this app disconnects."
            : "One-cancels-other is enforced by this client — it STOPS working if this app disconnects."}
        </p>
      ) : null}
      {attached.ocaType === 2 || attached.ocaType === 3 ? (
        <p className="mt-1 opacity-80">
          OCA type {attached.ocaType}: a fill proportionally REDUCES the sibling rather than
          cancelling it.
        </p>
      ) : null}
    </div>
  );
}

function Estimate({ estimate, currency }: { estimate: TicketEstimate; currency?: string }) {
  const cell = (label: string, v: ReactNode) =>
    v === undefined || v === null ? null : (
      <div>
        <dt className="text-[0.6875rem] uppercase tracking-wide text-secondary-500">{label}</dt>
        <dd className="tabular-nums">
          {currency}
          {v}
        </dd>
      </div>
    );

  return (
    <div data-fancy-trading-ticket-estimate="" className="space-y-2">
      <dl className="grid grid-cols-3 gap-2 text-xs">
        {cell("Notional", estimate.notional)}
        {cell("Margin", estimate.marginRequired)}
        {cell("Fees", estimate.fees)}
        {cell("Buying power after", estimate.buyingPowerAfter)}
        {estimate.liquidationPrice ? (
          <div>
            <dt className="text-[0.6875rem] uppercase tracking-wide text-secondary-500">
              Liquidation
            </dt>
            <dd className="tabular-nums">
              {currency}
              {estimate.liquidationPrice}
            </dd>
            {estimate.marginMode ? (
              <dd className="text-[0.625rem] opacity-80">
                {estimate.marginMode === "cross"
                  ? "cross margin — this moves whenever any other position moves"
                  : "isolated margin — a property of this position alone"}
              </dd>
            ) : null}
          </div>
        ) : null}
      </dl>

      {estimate.lookAhead ? (
        <dl
          data-fancy-trading-ticket-lookahead=""
          className="grid grid-cols-3 gap-2 border-t border-dashed border-secondary-200 pt-2 text-xs dark:border-secondary-800"
        >
          {cell("Look ahead funds", estimate.lookAhead.availableFunds)}
          {cell("Look ahead excess", estimate.lookAhead.excessLiquidity)}
          {estimate.lookAhead.nextChangeAt ? (
            <div>
              <dt className="text-[0.6875rem] uppercase tracking-wide text-secondary-500">
                Next change
              </dt>
              <dd>{new Date(estimate.lookAhead.nextChangeAt).toISOString().slice(11, 16)}</dd>
            </div>
          ) : null}
        </dl>
      ) : null}
    </div>
  );
}

function ApprovalDialog({
  intent,
  instrument,
  mode,
  onAccept,
  onReject,
}: {
  intent: OrderIntent;
  instrument: TicketInstrument;
  mode: TradingMode;
  onAccept: () => void;
  onReject: () => void;
}) {
  return (
    <div
      data-fancy-trading-approval={intent.clientOrderId}
      role="dialog"
      aria-modal="true"
      aria-label="Approve the agent's proposed order"
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"
    >
      <div className="w-full max-w-md rounded-lg bg-white p-4 shadow-xl dark:bg-secondary-900">
        <div className="flex items-center gap-2">
          <ModeMarker mode={mode} />
          <h2 className="text-sm font-semibold">An agent proposes this order</h2>
        </div>

        <dl className="mt-3 grid grid-cols-2 gap-2 text-sm">
          <dt className="text-secondary-500">Symbol</dt>
          <dd className="tabular-nums">{intent.symbol}</dd>
          <dt className="text-secondary-500">Side</dt>
          <dd>{intent.side}</dd>
          <dt className="text-secondary-500">Quantity</dt>
          <dd className="tabular-nums">{intent.qty.v.toString()}</dd>
          <dt className="text-secondary-500">Type</dt>
          <dd>{intent.type}</dd>
          {intent.limitPrice ? (
            <>
              <dt className="text-secondary-500">Limit</dt>
              <dd className="tabular-nums">
                {formatPrice(intent.limitPrice, instrument.priceDisplay)}
              </dd>
            </>
          ) : null}
          {intent.triggerPrice ? (
            <>
              <dt className="text-secondary-500">Trigger</dt>
              <dd className="tabular-nums">
                {formatPrice(intent.triggerPrice, instrument.priceDisplay)}
              </dd>
            </>
          ) : null}
          <dt className="text-secondary-500">Time in force</dt>
          <dd>{intent.tif}</dd>
        </dl>

        <p className="mt-3 text-xs text-secondary-600 dark:text-secondary-400">
          Agents propose; humans confirm. Approving this places a real order in {mode} mode.
        </p>

        <div className="mt-4 flex justify-end gap-2">
          <Button data-fancy-trading-approval-reject="" onClick={onReject}>
            Reject
          </Button>
          <Button data-fancy-trading-approval-accept="" color="green" onClick={onAccept}>
            Approve and place
          </Button>
        </div>
      </div>
    </div>
  );
}
